<?php
/* src/config/components.php - Auto-generated component services */
/* Generated by: php bin/console tabler:convert --type=components */
/* DO NOT EDIT - Re-run the converter to update */

declare(strict_types=1);

namespace Symfony\Component\DependencyInjection\Loader\Configurator;

use Survos\TablerBundle\Components;
use Survos\TablerBundle\Service\FixtureService;
use Symfony\Contracts\HttpClient\HttpClientInterface;

return static function (ContainerConfigurator $container): void {
    $services = $container->services()
        ->defaults()
            ->autowire()
            ->autoconfigure();

    // === Core Components (always present) ===
    
    $services->set(Components\TablerPage::class);
    $services->set(Components\MenuComponent::class)
        ->arg('$menuOptions', '%survos_tabler.menu_options%')
        ->arg('$helper', service('knp_menu.helper'))
        ->arg('$factory', service('knp_menu.factory'))
        ->arg('$eventDispatcher', service('event_dispatcher'));

    // === UI Components (simple, no data) ===
    
    $services->set(Components\Ui\AlertComponent::class);
    $services->set(Components\Ui\BadgeComponent::class);
    $services->set(Components\Ui\ButtonComponent::class);
    $services->set(Components\Ui\CardComponent::class);
    $services->set(Components\Ui\DropdownComponent::class);
    $services->set(Components\Ui\IconComponent::class);
    $services->set(Components\Ui\ModalComponent::class);
    $services->set(Components\Ui\ProgressComponent::class);
    $services->set(Components\Ui\SpinnerComponent::class);
    $services->set(Components\Ui\AvatarComponent::class);
    $services->set(Components\Ui\TabsComponent::class);
    $services->set(Components\Ui\AccordionComponent::class);
    
    // === Card Components (data-aware) ===
    
    $services->set(Components\Cards\UsersListComponent::class)
        ->arg('$fixtureService', service(FixtureService::class))
        ->arg('$httpClient', service(HttpClientInterface::class)->nullOnInvalid());

    $services->set(Components\Cards\ProfileComponent::class)
        ->arg('$fixtureService', service(FixtureService::class));

    $services->set(Components\Cards\ActivityComponent::class)
        ->arg('$fixtureService', service(FixtureService::class));

    $services->set(Components\Cards\CommentsComponent::class)
        ->arg('$fixtureService', service(FixtureService::class));

    $services->set(Components\Cards\TimelineComponent::class)
        ->arg('$fixtureService', service(FixtureService::class));

    // === Layout Components ===
    
    $services->set(Components\Layout\NavbarComponent::class);
    $services->set(Components\Layout\SidebarComponent::class);
    $services->set(Components\Layout\FooterComponent::class);
    $services->set(Components\Layout\PageHeaderComponent::class);
};
